//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Exam.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderCard
    {
        public ReaderCard()
        {
            this.TurnOver = new HashSet<TurnOver>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsBlock { get; set; }
    
        public virtual ICollection<TurnOver> TurnOver { get; set; }
    }
}
